# Generated by Django 4.1 on 2022-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="nickname",
            field=models.CharField(default="nickname", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="introduction",
            field=models.CharField(blank=True, max_length=300, verbose_name="个人简介"),
        ),
    ]
