# Generated by Django 4.1 on 2022-11-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userinfo_nickname_alter_userinfo_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="avatar",
            field=models.CharField(default="", max_length=2047),
            preserve_default=False,
        ),
    ]
