# Generated by Django 4.1 on 2022-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_remove_movie_vote_average_movie_vote_sum_and_more"),
        ("account", "0003_userinfo_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="prefer_genres",
            field=models.ManyToManyField(to="movie.genre"),
        ),
    ]
