# Generated by Django 4.1 on 2022-11-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_userinfo_like_celebrities_userinfo_like_movies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(default="initial.jpg", upload_to="User/avatar"),
        ),
    ]
