# Generated by Django 4.1 on 2022-11-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(
                default="User/avatar/initial.jpg", upload_to="User/avatar/"
            ),
        ),
    ]
