# Generated by Django 4.1 on 2022-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_remove_movie_vote_average_movie_vote_sum_and_more"),
        ("group", "0002_discussion"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discussion",
            name="title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="movie",
            field=models.ManyToManyField(to="movie.movie"),
        ),
    ]
