# Generated by Django 4.1 on 2022-11-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0004_alter_group_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="avatar",
            field=models.ImageField(
                default="Group/avatar/initial.jpg", upload_to="Group/avatar/"
            ),
        ),
    ]
