# Generated by Django 4.1 on 2022-12-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0006_discussion_create_at_discussion_update_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="name",
            field=models.CharField(default="test_group", max_length=30),
            preserve_default=False,
        ),
    ]
