# Generated by Django 4.1 on 2022-12-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0007_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion", name="likes", field=models.IntegerField(default=0),
        ),
    ]
