# Generated by Django 4.1 on 2022-12-21 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0008_alter_userinfo_avatar_and_more"),
        ("group", "0010_remove_discussion_likes_discussion_liked_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入小组时间"),
                ),
            ],
        ),
        migrations.RemoveField(model_name="group", name="members",),
        migrations.AddField(
            model_name="group",
            name="member",
            field=models.ManyToManyField(
                through="group.JoinTime",
                to=settings.AUTH_USER_MODEL,
                verbose_name="小组成员",
            ),
        ),
        migrations.AddField(
            model_name="jointime",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="group.group"
            ),
        ),
        migrations.AddField(
            model_name="jointime",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
