# Generated by Django 4.1 on 2022-12-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0012_rename_member_group_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="title",
            field=models.CharField(max_length=500, verbose_name="标题"),
        ),
    ]
