# Generated by Django 4.1 on 2022-10-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="celebrity",
            name="image",
            field=models.CharField(default="", max_length=2047),
            preserve_default=False,
        ),
    ]
