# Generated by Django 4.1 on 2022-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0003_alter_celebrity_celebrity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity",
            name="introduction",
            field=models.CharField(max_length=2047),
        ),
    ]
