# Generated by Django 4.1 on 2022-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0004_alter_celebrity_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity", name="introduction", field=models.TextField(),
        ),
    ]
