# Generated by Django 4.1 on 2022-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0005_alter_celebrity_introduction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celebrity", old_name="introduction", new_name="biography",
        ),
        migrations.RenameField(
            model_name="celebrity", old_name="image", new_name="image_path",
        ),
        migrations.AddField(
            model_name="celebrity",
            name="birthday",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="celebrity",
            name="career",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="celebrity",
            name="gender",
            field=models.SmallIntegerField(choices=[(1, "男"), (2, "女")], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="celebrity",
            name="place_of_birth",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
