# Generated by Django 4.1 on 2022-10-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0006_rename_introduction_celebrity_biography_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celebrity", old_name="image_path", new_name="image",
        ),
    ]
