# Generated by Django 4.1 on 2022-10-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0007_rename_image_path_celebrity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="birthday",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="career",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="gender",
            field=models.SmallIntegerField(choices=[(0, "未知"), (1, "男"), (2, "女")]),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="image",
            field=models.CharField(blank=True, max_length=2047),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
