# Generated by Django 4.1 on 2022-11-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "celebrity",
            "0008_alter_celebrity_biography_alter_celebrity_birthday_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CelebrityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=2047)),
                (
                    "celebrity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="celebrity.celebrity",
                    ),
                ),
            ],
        ),
    ]
