# Generated by Django 4.1 on 2022-12-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0009_celebrityimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="celebrity",
            options={"verbose_name": "影人", "verbose_name_plural": "影人"},
        ),
        migrations.AlterModelOptions(
            name="celebrityimage",
            options={"verbose_name": "影人图片", "verbose_name_plural": "影人图片"},
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="biography",
            field=models.TextField(blank=True, verbose_name="介绍"),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="birthday",
            field=models.CharField(blank=True, max_length=40, verbose_name="出生日期"),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="career",
            field=models.CharField(blank=True, max_length=255, verbose_name="职业"),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="celebrity_name",
            field=models.CharField(max_length=60, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "未知"), (1, "男"), (2, "女")], verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="image",
            field=models.CharField(blank=True, max_length=2047, verbose_name="图片路径"),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=255, verbose_name="出生地"),
        ),
        migrations.AlterField(
            model_name="celebrityimage",
            name="celebrity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="celebrity.celebrity",
                verbose_name="影人",
            ),
        ),
        migrations.AlterField(
            model_name="celebrityimage",
            name="path",
            field=models.CharField(max_length=2047, verbose_name="图片路径"),
        ),
    ]
