# Generated by Django 4.1 on 2022-10-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("celebrity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=30)),
                ("introduction", models.CharField(max_length=1023)),
                ("release_time", models.CharField(max_length=20)),
                ("duration", models.CharField(max_length=20)),
                ("image", models.CharField(max_length=2047)),
                ("region", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.SmallIntegerField(choices=[(0, "导演"), (1, "编剧"), (2, "参演")]),
                ),
                (
                    "celebrity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="celebrity.celebrity",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="celebrities",
            field=models.ManyToManyField(
                through="movie.Position", to="celebrity.celebrity"
            ),
        ),
    ]
