# Generated by Django 4.1 on 2022-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="region", field=models.CharField(max_length=60),
        ),
    ]
