# Generated by Django 4.1 on 2022-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_movie_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_name",
            field=models.CharField(max_length=60),
        ),
    ]
