# Generated by Django 4.1 on 2022-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_movie_introduction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="introduction", new_name="overview",
        ),
        migrations.RenameField(
            model_name="movie", old_name="release_time", new_name="release_date",
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
