# Generated by Django 4.1 on 2022-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_rename_introduction_movie_overview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(to="movie.genre"),
        ),
    ]
