# Generated by Django 4.1 on 2022-10-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_genre_movie_tags"),
    ]

    operations = [
        migrations.RenameField(model_name="movie", old_name="tags", new_name="genres",),
    ]
