# Generated by Django 4.1 on 2022-11-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_rename_tags_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="vote_average",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="movie", name="vote_count", field=models.IntegerField(default=0),
        ),
    ]
