# Generated by Django 4.1 on 2022-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_movietrailer_movieimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="vote_average",),
        migrations.AddField(
            model_name="movie",
            name="vote_sum",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
