# Generated by Django 4.1 on 2022-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0015_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="languages",
            field=models.ManyToManyField(to="movie.language"),
        ),
    ]
