# Generated by Django 4.1 on 2022-12-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "celebrity",
            "0010_alter_celebrity_options_alter_celebrityimage_options_and_more",
        ),
        ("movie", "0017_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "电影类型", "verbose_name_plural": "电影类型"},
        ),
        migrations.AlterModelOptions(
            name="movie", options={"verbose_name": "电影", "verbose_name_plural": "电影"},
        ),
        migrations.AlterModelOptions(
            name="movieimage",
            options={"verbose_name": "电影图片", "verbose_name_plural": "电影图片"},
        ),
        migrations.AlterModelOptions(
            name="movietrailer",
            options={"verbose_name": "电影预告片", "verbose_name_plural": "电影预告片"},
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=20, verbose_name="类型"),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=20, verbose_name="语言"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="celebrities",
            field=models.ManyToManyField(
                through="movie.Position", to="celebrity.celebrity", verbose_name="演职人员"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.SmallIntegerField(verbose_name="时长"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movie.genre", verbose_name="类型"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.CharField(max_length=2047, verbose_name="封面图片路径"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="languages",
            field=models.ManyToManyField(to="movie.language", verbose_name="语言"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movie_name",
            field=models.CharField(max_length=60, verbose_name="电影名"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="region",
            field=models.CharField(max_length=60, verbose_name="地区"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(verbose_name="发行日期"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_count",
            field=models.BigIntegerField(default=0, verbose_name="评分数"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_sum",
            field=models.BigIntegerField(default=0, verbose_name="评分总和"),
        ),
        migrations.AlterField(
            model_name="movieimage",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="电影",
            ),
        ),
        migrations.AlterField(
            model_name="movieimage",
            name="path",
            field=models.CharField(max_length=2047, verbose_name="电影图片路径"),
        ),
        migrations.AlterField(
            model_name="movietrailer",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="电影",
            ),
        ),
        migrations.AlterField(
            model_name="movietrailer",
            name="path",
            field=models.CharField(max_length=2047, verbose_name="电影预告片路径"),
        ),
    ]
