# Generated by Django 4.1 on 2022-12-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0018_alter_genre_options_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="vote_count",),
        migrations.RemoveField(model_name="movie", name="vote_sum",),
    ]
