# Generated by Django 4.1 on 2022-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0019_remove_movie_vote_count_remove_movie_vote_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.BigIntegerField(default=0, verbose_name="评分数"),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_sum",
            field=models.BigIntegerField(default=0, verbose_name="评分总和"),
        ),
    ]
