# Generated by Django 4.1 on 2022-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0020_movie_vote_count_movie_vote_sum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="类型"),
        ),
    ]
