# Generated by Django 4.1 on 2022-11-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
