# Generated by Django 4.1 on 2022-11-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0006_rename_user_info_reply_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating", old_name="user_info", new_name="author",
        ),
    ]
