# Generated by Django 4.1 on 2022-11-18 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0007_rename_user_info_rating_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rating",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
