# Generated by Django 4.1 on 2022-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0008_rating_create_at_rating_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review", name="likes", field=models.IntegerField(default=0),
        ),
    ]
