# Generated by Django 4.1 on 2022-12-20 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movie", "0018_alter_genre_options_alter_movie_options_and_more"),
        ("comment", "0009_review_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating", options={"verbose_name": "短评", "verbose_name_plural": "短评"},
        ),
        migrations.AlterModelOptions(
            name="reply", options={"verbose_name": "回复", "verbose_name_plural": "回复"},
        ),
        migrations.AlterModelOptions(
            name="review", options={"verbose_name": "影评", "verbose_name_plural": "影评"},
        ),
        migrations.AlterField(
            model_name="rating",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="content",
            field=models.CharField(blank=True, max_length=350, verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建于"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="电影",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="修改于"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.SmallIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="评分",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建于"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="comment.review",
                verbose_name="回复的影评",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="修改于"),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="review",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建于"),
        ),
        migrations.AlterField(
            model_name="review",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="电影",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=50, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="review",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="修改于"),
        ),
    ]
