# Generated by Django 4.1 on 2022-12-20 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0010_alter_rating_options_alter_reply_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="likes",),
        migrations.AddField(
            model_name="review",
            name="liked_user",
            field=models.ManyToManyField(
                related_name="liked_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="点过赞的用户",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
    ]
