# Generated by Django 4.1 on 2022-12-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0011_remove_review_likes_review_liked_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.SmallIntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="评分",
            ),
        ),
    ]
