# Generated by Django 4.1 on 2022-12-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0013_alter_review_author_alter_review_liked_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=500, verbose_name="标题"),
        ),
    ]
